const BLOCKS = {
  wblack: "blocks/Wool_Black.png",
  wblue: "blocks/Wool_Blue.png",
  wbrown: "blocks/Wool_Brown.png",
  wcyan: "blocks/Wool_Cyan.png",
  wgray: "blocks/Wool_Gray.png",
  wgreen: "blocks/Wool_Green.png",
  wlightblue: "blocks/Wool_LightBlue.png",
  wlightgray: "blocks/Wool_LightGray.png",
  wlime: "blocks/Wool_Lime.png",
  wmagenta: "blocks/Wool_Magenta.png",
  worange: "blocks/Wool_Orange.png",
  wpink: "blocks/Wool_Pink.png",
  wpurple: "blocks/Wool_Purple.png",
  wred: "blocks/Wool_Red.png",
  wwhite: "blocks/Wool_White.png",
  wyellow: "blocks/Wool_Yellow.png",
  twhite: "blocks/Terracotta_White.png",
};